### ISSUE TITLE
reading data from FANUC OI Mate-TD

### ISSUE THREAD

**Issue by sabriuzuner** [yuki-meguro/Fanuc-point-save#1]
Hello,

I need help with something related to my thesis.
I am using a CNC controlled lathe with a Fanuc OI Mate controller. I'm trying to get realtime data such as feed rate and spindle speed at the time of processing using OPC Server. I can get S and T code data (eg #4319 spindle speed) from system variables without any problem. However, I cannot access the “actual values” of these variables because I do not know their addresses. I've gone through the controller's manual and other related PDF files and I'm pretty confused. For example, how can I measure the instantaneous loads on each axis? Do I need to make any changes in CNC parameters, such as reading PMC values over Ethernet? I have no idea about Parameter. Just try to change looking for the Manuel if I am sure.
I guess I may be having this problem because of the difference in receiving data over NC and PMC?
For example, while System Variable values allow me to receive data via NC, is data received via PMC with address values that I do not know?
I need your help on this. Thanks.[](ur
![243821866_3028171647464382_2537189109467723776_n](https://user-images.githubusercontent.com/91631617/135332254-72feb843-8f36-4cb7-9e21-23d8bc5fa87a.jpg)
l)

**Comment by yuki-meguro** [comment]
Sorry, this program is for robots only.
